# Generated by Django 2.0.1 on 2018-06-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180618_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
