# Generated by Django 2.0.1 on 2018-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_for_college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Notes_for_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=500)),
                ('level', models.IntegerField(max_length=2)),
                ('school', models.CharField(max_length=35)),
            ],
        ),
    ]
