# Generated by Django 2.0.1 on 2018-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20180313_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='number_of_right_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='number_of_wrong_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='positive_marks',
            field=models.IntegerField(default=0),
        ),
    ]
