# Generated by Django 2.0.1 on 2018-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_remove_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blogimage',
        ),
    ]
