# Generated by Django 2.0.1 on 2018-05-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20180525_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_answered_by',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment_answered_by',
        ),
    ]
