# Generated by Django 2.0.1 on 2018-05-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0011_auto_20180530_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_answered_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_assignment', models.IntegerField()),
                ('answer', models.CharField(max_length=400)),
                ('marks', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
