# Generated by Django 2.0.1 on 2018-05-31 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0013_auto_20180531_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_answered_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_assignment', models.CharField(max_length=30)),
                ('assignment_id', models.IntegerField()),
                ('answer_string', models.CharField(max_length=400)),
                ('marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('submitted', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
