# Generated by Django 2.0.1 on 2018-06-05 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0015_auto_20180605_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quotes', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('background_image', models.ImageField(upload_to='blogger_image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
