# Generated by Django 2.0.1 on 2018-06-15 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0024_auto_20180615_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment_answered_by',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 13, 22, 40, 727423, tzinfo=utc)),
        ),
    ]
