# Generated by Django 2.0.1 on 2018-06-15 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0025_auto_20180615_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_answered_by',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
