# Generated by Django 2.0.1 on 2018-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0026_auto_20180615_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created']},
        ),
    ]
